/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package allasKereso;

import java.awt.Desktop;
import java.io.IOException;
import java.net.URI;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author SasGyula(SZOFT_2023_
 */
public class projekt extends javax.swing.JFrame {

        String vezeteknev = "";
        String keresztnev = "";
        String szulDatum = "";
        String email = "";
        String telSzam = "";
        String munka = "";
    public projekt() {
        initComponents();

        munkak();
        munka1Leiras();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        lblKep = new javax.swing.JLabel();
        lblNev = new javax.swing.JLabel();
        pnlMunkak = new javax.swing.JPanel();
        rdbMunka1 = new javax.swing.JRadioButton();
        rdbMunka2 = new javax.swing.JRadioButton();
        rdbMunka3 = new javax.swing.JRadioButton();
        rdbMunka4 = new javax.swing.JRadioButton();
        jPanel2 = new javax.swing.JPanel();
        lblVezeteknev = new javax.swing.JLabel();
        lblKeresztnev = new javax.swing.JLabel();
        lblSzulDat = new javax.swing.JLabel();
        lblEmail = new javax.swing.JLabel();
        lblTelSzam = new javax.swing.JLabel();
        txfSzulD = new javax.swing.JTextField();
        txfKeresztnev = new javax.swing.JTextField();
        txfVezeteknev = new javax.swing.JTextField();
        txfEmail = new javax.swing.JTextField();
        txfTel = new javax.swing.JTextField();
        pnlAllasok = new javax.swing.JPanel();
        cmbAllasok = new javax.swing.JComboBox<>();
        lblLeiras = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txaLeiras = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        lblKep.setIcon(new javax.swing.ImageIcon("C:\\Users\\ADMIN\\OneDrive - SZÁMALK-Szalézi Technikum és Szakgimnázium\\Dokumentumok\\Java\\AllaskeresoProject\\Allaskereso\\kepek\\kep1.png")); // NOI18N

        lblNev.setText("<html>\n<b style=\"font-size:20;\">WorkFinder</b>\n</html>");

        pnlMunkak.setBorder(javax.swing.BorderFactory.createTitledBorder("Munkák"));

        buttonGroup1.add(rdbMunka1);
        rdbMunka1.setSelected(true);
        rdbMunka1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                rdbMunka1ItemStateChanged(evt);
            }
        });

        buttonGroup1.add(rdbMunka2);
        rdbMunka2.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                rdbMunka2ItemStateChanged(evt);
            }
        });

        buttonGroup1.add(rdbMunka3);
        rdbMunka3.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                rdbMunka3ItemStateChanged(evt);
            }
        });

        buttonGroup1.add(rdbMunka4);
        rdbMunka4.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                rdbMunka4ItemStateChanged(evt);
            }
        });

        javax.swing.GroupLayout pnlMunkakLayout = new javax.swing.GroupLayout(pnlMunkak);
        pnlMunkak.setLayout(pnlMunkakLayout);
        pnlMunkakLayout.setHorizontalGroup(
            pnlMunkakLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMunkakLayout.createSequentialGroup()
                .addGroup(pnlMunkakLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rdbMunka1)
                    .addComponent(rdbMunka2)
                    .addComponent(rdbMunka3)
                    .addComponent(rdbMunka4))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlMunkakLayout.setVerticalGroup(
            pnlMunkakLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMunkakLayout.createSequentialGroup()
                .addComponent(rdbMunka1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rdbMunka2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rdbMunka3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rdbMunka4)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Adatok"));

        lblVezeteknev.setText("Vezetéknév");

        lblKeresztnev.setText("Keresztnév");

        lblSzulDat.setText("Születési dátum");

        lblEmail.setText("Email");

        lblTelSzam.setText("Telefonszám");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblVezeteknev)
                                    .addComponent(lblTelSzam)
                                    .addComponent(lblEmail))
                                .addGap(23, 23, 23))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addComponent(lblSzulDat)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txfSzulD)
                            .addComponent(txfVezeteknev)
                            .addComponent(txfEmail)
                            .addComponent(txfTel, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(lblKeresztnev)
                        .addGap(33, 33, 33)
                        .addComponent(txfKeresztnev)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txfVezeteknev, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblVezeteknev))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txfKeresztnev, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblKeresztnev))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txfSzulD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblSzulDat))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txfEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblEmail))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTelSzam)
                    .addComponent(txfTel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnlAllasok.setBorder(javax.swing.BorderFactory.createTitledBorder("Állás"));

        cmbAllasok.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "IT", "Marketing", "Fizikai", "Vendéglátás" }));
        cmbAllasok.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbAllasokItemStateChanged(evt);
            }
        });

        javax.swing.GroupLayout pnlAllasokLayout = new javax.swing.GroupLayout(pnlAllasok);
        pnlAllasok.setLayout(pnlAllasokLayout);
        pnlAllasokLayout.setHorizontalGroup(
            pnlAllasokLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlAllasokLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(cmbAllasok, 0, 128, Short.MAX_VALUE)
                .addContainerGap())
        );
        pnlAllasokLayout.setVerticalGroup(
            pnlAllasokLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlAllasokLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(cmbAllasok, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15))
        );

        jButton1.setText("Kész!");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        txaLeiras.setColumns(20);
        txaLeiras.setLineWrap(true);
        txaLeiras.setRows(5);
        jScrollPane1.setViewportView(txaLeiras);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(lblLeiras))
                            .addComponent(jScrollPane1)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lblNev, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 98, Short.MAX_VALUE))
                                    .addComponent(pnlMunkak, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(pnlAllasok, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblKep))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblNev, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(pnlMunkak, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(pnlAllasok, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblLeiras)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblKep)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cmbAllasokItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbAllasokItemStateChanged
        munkak();
        munka1Leiras();
        munka2Leiras();
        munka3Leiras();
        munka4Leiras();

    }//GEN-LAST:event_cmbAllasokItemStateChanged

    private void rdbMunka1ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_rdbMunka1ItemStateChanged
        munka1Leiras(); 
    }//GEN-LAST:event_rdbMunka1ItemStateChanged

    private void munka1Leiras() {
        if (rdbMunka1.getText() == "Codeluxe Solutions Kft." && rdbMunka1.isSelected()){
            txaLeiras.setText("A Codeluxe Solutions Kft. egy dinamikus IT vállalat, amely a legújabb technológiai trendekre és innovációkra összpontosít. Kiváló fejlesztőink és tervezőink a CodeCoins, a vállalat saját kriptovalutájában részesülnek, amelynek értéke folyamatosan emelkedik a kreativitás és az eredményesség alapján.");
        } else if (rdbMunka1.getText() == "BrandVibe Creations Kft." && rdbMunka1.isSelected()){
            txaLeiras.setText("A BrandVibe Creations Kft. egy kreatív marketingügynökség, amely az érzelmekre és hangulatokra fókuszál. Munkatársaink nem csak pénzben, hanem VibePoints-ben is részesülnek, amelyeket különböző brandépítő rendezvényeken és szakmai tréningeken válthatnak be.");
        } else if (rdbMunka1.getText() == "HeavyLift Workers Kft." && rdbMunka1.isSelected()){
            txaLeiras.setText("A HeavyLift Workers Kft. egy fizikai munkára specializálódott vállalat, ahol munkatársaink hagyományos készpénzben kapják meg fizetésüket. A vállalat magas színvonalú emelőgépeket és nehézgépeket kezel, és a munkavállalók a szakmai tapasztalatuknak megfelelően kapnak bérfizetést.");
        } else if (rdbMunka1.getText() == "TastyBites Café & Bistro" && rdbMunka1.isSelected()){
            txaLeiras.setText("A TastyBites Café & Bistro egy étterem, ahol a munkatársak a szakmai elismeréseken túl különféle extra szolgáltatásokban részesülnek, például ingyenes étel- és italfogyasztásban, speciális tréningeken való részvétel lehetőségében vagy szakácsi műhelyekben való részvételben.");
        }
    }

    private void rdbMunka2ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_rdbMunka2ItemStateChanged
        munka2Leiras();
    }//GEN-LAST:event_rdbMunka2ItemStateChanged

    private void munka2Leiras() {
        if (rdbMunka2.getText() == "QuantumByte Labs Zrt." && rdbMunka2.isSelected()) {
            txaLeiras.setText("A QuantumByte Labs Zrt. a kvantumszámítástechnika területén vezető szerepet tölt be. Munkatársaink nem csupán pénzben, hanem Quantum Credits-ben is részesülnek, melyekkel nemcsak a vállalat által kínált termékeket, szolgáltatásokat vásárolhatják meg, hanem saját fejlesztéseikhez is hozzáférhetnek.");
        } else if (rdbMunka2.getText() == "TrendSpark Marketing Agency" && rdbMunka2.isSelected()) {
            txaLeiras.setText("A TrendSpark Marketing Agency a piactrendek és innovációk terén jár az élen. Munkatársaink a TrendCoins kriptovalutában kapják meg fizetésüket, és ezt a virtuális pénzt trendi szolgáltatások és exkluzív marketing eszközök vásárlására használhatják fel." );
        } else if (rdbMunka2.getText() == "QuickHands Labor Solutions" && rdbMunka2.isSelected()) {
            txaLeiras.setText("A QuickHands Labor Solutions Zrt. a gyors fizikai munkára specializálódott vállalat, ahol a munkavállalók rendszeres banki átutalással kapják meg béruket. A vállalat rugalmas munkaidőt biztosít, és a fizetés a munkatapasztalat és a végzett feladatok alapján változik.");
        } else if (rdbMunka2.getText() == "GourmetCraft Catering Ltd." && rdbMunka2.isSelected()) {
            txaLeiras.setText("A GourmetCraft Catering Ltd. a gasztronómia területén tevékenykedik, és a munkavállalók étteremkedvezményeket élvezhetnek a vállalat által üzemeltetett éttermekben. Ezen kívül lehetőségük van részt venni különleges rendezvényeken és ízléses kóstolókon.");
        }
    }

    private void rdbMunka3ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_rdbMunka3ItemStateChanged
        munka3Leiras();
    }//GEN-LAST:event_rdbMunka3ItemStateChanged

    private void munka3Leiras() {
        if(rdbMunka3.getText() == "CyberGuard Innovations Inc." && rdbMunka3.isSelected()){
            txaLeiras.setText("A CyberGuard Innovations Inc. az információbiztonság és a kiberbiztonság terén áll az élen. Munkatársaink nem csak versenyképes fizetést kapnak, hanem CyberCredits-et is, melyeket a vállalat által kínált speciális tréningekre és szolgáltatásokra válthatnak be.");
        }else if (rdbMunka3.getText() == "BuzzCraft Media Solutions Ltd." && rdbMunka3.isSelected()){
            txaLeiras.setText("A BuzzCraft Media Solutions Ltd. egy médiaorientált marketingügynökség, amely munkatársainak nem csak a hagyományos fizetését, hanem BuzzTokens-et is biztosít. Ezt a különleges kriptovalutát buzzkampányok és egyedi marketingprojektek részvételére használhatják fel.");
        } else if (rdbMunka3.getText() == "SimpleLabor Corp." && rdbMunka3.isSelected()){
            txaLeiras.setText("A SimpleLabor Corp. egyszerű fizikai munkákra specializálódott, ahol a munkavállalók választhatnak a készpénzes vagy banki átutalásos fizetés között. A vállalat olyan egyszerű munkafolyamatokra összpontosít, mint a csomagolás, rakodás és egyéb alapvető fizikai feladatok.");
        } else if (rdbMunka3.getText() == "FreshFlavors Boulangerie" && rdbMunka3.isSelected()){
            txaLeiras.setText("A FreshFlavors Boulangerie egy pékség, ahol a munkatársak rendszeres ízteszteken vesznek részt és lehetőségük van a termékfejlesztési projektekben való részvételre. A sikeresen bevezetett termékekért és kreatív receptekért járó elismerések alkotják a fizetési rendszert.");
        }
    }

    private void rdbMunka4ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_rdbMunka4ItemStateChanged
        munka4Leiras();
    }//GEN-LAST:event_rdbMunka4ItemStateChanged

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
    valasztottMunka();
    vezeteknev = txfVezeteknev.getText();
    keresztnev = txfKeresztnev.getText();
    telSzam = txfTel.getText();
    email = txfEmail.getText();
    szulDatum = txfSzulD.getText();
    if (vezeteknev.length() == 0 || keresztnev.length() == 0 || telSzam.length() == 0 || email.length() == 0 || szulDatum.length() == 0){
        JOptionPane.showMessageDialog(rootPane, "Hiányos adatok!");
    } else{
        JOptionPane.showMessageDialog(rootPane, "Az adatokat sikeresen felvittük! Hamarosan emailban értesítjük!\n" + vezeteknev + " " + keresztnev + "\n" + szulDatum + "\n" + email + "\n" + telSzam + "\n" + munka );
        System.exit(0);
    }
    
    }//GEN-LAST:event_jButton1ActionPerformed

    private void valasztottMunka() {
        if (rdbMunka1.isSelected()){
            munka = rdbMunka1.getText();
        }else if(rdbMunka2.isSelected()){
            munka = rdbMunka2.getText();
        }else if(rdbMunka3.isSelected()){
            munka = rdbMunka3.getText();
        }else if(rdbMunka4.isSelected()){
            munka = rdbMunka4.getText();
        }
    }

    private void munka4Leiras() {
        if(rdbMunka4.getText() == "RoboOps Dynamics Ltd." && rdbMunka4.isSelected()){
            txaLeiras.setText("A RoboOps Dynamics Ltd. a robotikára és automatizálásra összpontosít. Munkatársaink a RoboTokens kriptovalutában részesülnek, melyet saját fejlesztéseikben használhatnak fel. Emellett a vállalat minden hónapban rendez robotprogramozó versenyt, ahol különböző szintekű és típusú robotokat kell programozni a leginnovatívabb módon.");
        }else if (rdbMunka4.getText() == "SocialPulse Dynamics Inc." && rdbMunka4.isSelected()){
            txaLeiras.setText("A SocialPulse Dynamics Inc. a közösségi médiára és online marketingre összpontosít. Munkatársaink a SocialCredits kriptovalutában kapják meg jutalmukat, amelyeket a vállalat által szervezett influencer eseményeken és szponzorációs lehetőségeken való részvételre, valamint a saját szociális média kampányaikhoz használhatnak fel.");
        } else if (rdbMunka4.getText() == "SwiftHands Workforce Ltd." && rdbMunka4.isSelected()){
            txaLeiras.setText("A SwiftHands Workforce Ltd. egy rugalmas fizikai munkára szakosodott vállalkozás, ahol a munkatársak a munkájukért készpénzben vagy csekken kapják meg fizetésüket. A vállalat különféle iparágakban nyújt fizikai munka lehetőségeket, és a bérszint a feladatok típusától függ.");
        } else if (rdbMunka4.getText() == "UrbanEats Food Truck" && rdbMunka4.isSelected()){
            txaLeiras.setText("Az UrbanEats Food Truck egy mozgó vendéglátóegység, ahol a munkavállalók speciális ételtruck-előnyöket kapnak, mint például ingyenes étel- és italfogyasztás a food truck kínálatából. Ráadásul a munkatársak részt vehetnek különféle fesztiválokon és rendezvényeken.");
        }
    }

    private void munkak() {
        if (cmbAllasok.getSelectedIndex() == 0){
            rdbMunka1.setText("Codeluxe Solutions Kft.");
            rdbMunka2.setText("QuantumByte Labs Zrt.");
            rdbMunka3.setText("CyberGuard Innovations Inc.");
            rdbMunka4.setText("RoboOps Dynamics Ltd.");
        } else if(cmbAllasok.getSelectedIndex() == 1) {
            rdbMunka1.setText("BrandVibe Creations Kft.");
            rdbMunka2.setText("TrendSpark Marketing Agency");
            rdbMunka3.setText("BuzzCraft Media Solutions Ltd.");
            rdbMunka4.setText("SocialPulse Dynamics Inc.");
        } else if(cmbAllasok.getSelectedIndex() == 2){
            rdbMunka1.setText("HeavyLift Workers Kft.");
            rdbMunka2.setText("QuickHands Labor Solutions");
            rdbMunka3.setText("SimpleLabor Corp.");
            rdbMunka4.setText("SwiftHands Workforce Ltd.");
        }else if(cmbAllasok.getSelectedIndex() == 3){
            rdbMunka1.setText("TastyBites Café & Bistro");
            rdbMunka2.setText("GourmetCraft Catering Ltd.");
            rdbMunka3.setText("FreshFlavors Boulangerie");
            rdbMunka4.setText("UrbanEats Food Truck");
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(projekt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(projekt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(projekt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(projekt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new projekt().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> cmbAllasok;
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblKep;
    private javax.swing.JLabel lblKeresztnev;
    private javax.swing.JLabel lblLeiras;
    private javax.swing.JLabel lblNev;
    private javax.swing.JLabel lblSzulDat;
    private javax.swing.JLabel lblTelSzam;
    private javax.swing.JLabel lblVezeteknev;
    private javax.swing.JPanel pnlAllasok;
    private javax.swing.JPanel pnlMunkak;
    private javax.swing.JRadioButton rdbMunka1;
    private javax.swing.JRadioButton rdbMunka2;
    private javax.swing.JRadioButton rdbMunka3;
    private javax.swing.JRadioButton rdbMunka4;
    private javax.swing.JTextArea txaLeiras;
    private javax.swing.JTextField txfEmail;
    private javax.swing.JTextField txfKeresztnev;
    private javax.swing.JTextField txfSzulD;
    private javax.swing.JTextField txfTel;
    private javax.swing.JTextField txfVezeteknev;
    // End of variables declaration//GEN-END:variables
}
